# Generated by Django 5.2.10 on 2026-05-06 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdc_id', models.IntegerField(blank=True, null=True)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('protein_g', models.FloatField(blank=True, null=True)),
                ('carbs_g', models.FloatField(blank=True, null=True)),
                ('fat_g', models.FloatField(blank=True, null=True)),
                ('fiber_g', models.FloatField(blank=True, null=True)),
                ('sugar_g', models.FloatField(blank=True, null=True)),
                ('sodium_mg', models.FloatField(blank=True, null=True)),
                ('serving_size', models.FloatField(blank=True, null=True)),
                ('serving_unit', models.CharField(blank=True, max_length=50)),
                ('food_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='food.fooditem')),
            ],
        ),
    ]
