# Generated by Django 5.2.10 on 2026-02-12 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='food.foodtype')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='food.location')),
            ],
        ),
    ]
