# Generated by Django 5.2.10 on 2026-01-22 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='curr_date',
            new_name='date',
        ),
    ]
