# Generated by Django 5.2.10 on 2026-03-12 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagged_on', models.DateField(auto_now_add=True)),
                ('tagged_by', models.CharField(blank=True, max_length=50)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.fooditem')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.tag')),
            ],
            options={
                'unique_together': {('food_item', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='fooditem',
            name='tags',
            field=models.ManyToManyField(related_name='food_items', through='food.FoodItemTag', to='food.tag'),
        ),
    ]
