# Generated by Django 5.2.10 on 2026-03-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_tag_fooditemtag_fooditem_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_expiring_soon',
            field=models.BooleanField(default=False),
        ),
    ]
